# Zabbix Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: zabbix
  labels:
    name: zabbix

---
# Zabbix Database Secrets
apiVersion: v1
kind: Secret
metadata:
  name: zabbix-db-secret
  namespace: zabbix
type: Opaque
data:
  # mysql-root-password: base64 encoded password
  # mysql-password: base64 encoded password
  # Default passwords (CHANGE THESE IN PRODUCTION!)
  # Root password: "ZabbixRoot123!" -> WmFiYml4Um9vdDEyMyE=
  # Zabbix user password: "zabbix123!" -> emFiYml4MTIzIQ==
  mysql-root-password: WmFiYml4Um9vdDEyMyE=
  mysql-password: emFiYml4MTIzIQ==

---
# Zabbix ConfigMap for additional configurations
apiVersion: v1
kind: ConfigMap
metadata:
  name: zabbix-config
  namespace: zabbix
data:
  # Additional Zabbix server configurations can be added here
  zabbix_server.conf: |
    LogFile=/tmp/zabbix_server.log
    LogFileSize=10
    PidFile=/tmp/zabbix_server.pid
    SocketDir=/tmp
    DBHost=zabbix-mysql
    DBName=zabbix
    DBUser=zabbix
    DBPassword=zabbix123!
    DBSocket=/tmp/mysql.sock
    DBPort=3306
    StartPollers=5
    StartIPMIPollers=0
    StartPollersUnreachable=1
    StartTrappers=5
    StartPingers=1
    StartDiscoverers=1
    StartHTTPPollers=1
    StartTimers=1
    StartEscalators=1
    StartAlerters=3
    JavaGateway=zabbix-java-gateway
    JavaGatewayPort=10052
    StartJavaPollers=5
    StartVMwareCollectors=0
    VMwareFrequency=60
    VMwarePerfFrequency=60
    VMwareCacheSize=8M
    VMwareTimeout=10
    SNMPTrapperFile=/tmp/zabbix_traps.tmp
    StartSNMPTrapper=0
    ListenIP=0.0.0.0
    ListenPort=10051
    HousekeepingFrequency=1
    MaxHousekeeperDelete=5000
    SenderFrequency=30
    CacheSize=8M
    CacheUpdateFrequency=60
    StartDBSyncers=4
    HistoryCacheSize=16M
    HistoryIndexCacheSize=4M
    TrendCacheSize=4M
    ValueCacheSize=8M
    Timeout=4
    TrapperTimeout=300
    UnreachablePeriod=45
    UnavailableDelay=60
    UnreachableDelay=15
    AlertScriptsPath=/usr/lib/zabbix/alertscripts
    ExternalScripts=/usr/lib/zabbix/externalscripts
    FpingLocation=/usr/sbin/fping
    Fping6Location=/usr/sbin/fping6
    SSHKeyLocation=
    LogSlowQueries=3000
    TmpDir=/tmp
    StartProxyPollers=1
    ProxyConfigFrequency=3600
    ProxyDataFrequency=1
    AllowRoot=0
    User=zabbix
    Include=/usr/local/etc/zabbix_server.conf.d/*.conf
    SSLCertLocation=/usr/local/share/zabbix/ssl/certs/
    SSLKeyLocation=/usr/local/share/zabbix/ssl/keys/
    SSLCALocation=/usr/local/share/zabbix/ssl/ssl_ca/
    LoadModulePath=/var/lib/zabbix/modules
    TLSCAFile=
    TLSCRLFile=
    TLSCertFile=
    TLSKeyFile=
