apiVersion: batch/v1
kind: Job
metadata:
  name: zabbix-db-init
  namespace: zabbix
  labels:
    app: zabbix-db-init
spec:
  template:
    metadata:
      labels:
        app: zabbix-db-init
    spec:
      restartPolicy: Never
      containers:
      - name: mysql-client
        image: mysql:8.0
        command: 
        - /bin/bash
        - -c
        - |
          echo "Waiting for MySQL to be ready..."
          until mysql -h zabbix-mysql -u zabbix -pzabbix_password -e "SELECT 1" > /dev/null 2>&1; do
            echo "Still waiting for MySQL..."
            sleep 10
          done
          
          echo "MySQL is ready, checking database contents..."
          TABLES_COUNT=$(mysql -h zabbix-mysql -u zabbix -pzabbix_password -D zabbix -e "SHOW TABLES;" 2>/dev/null | wc -l)
          echo "Found $TABLES_COUNT tables in database"
          
          if [ "$TABLES_COUNT" -gt 5 ]; then
            echo "Database appears to be initialized already"
            exit 0
          fi
          
          echo "Creating minimal database structure..."
          mysql -h zabbix-mysql -u zabbix -pzabbix_password zabbix -e "
            CREATE TABLE IF NOT EXISTS users (
              userid bigint unsigned NOT NULL AUTO_INCREMENT,
              username varchar(100) NOT NULL DEFAULT '',
              name varchar(100) NOT NULL DEFAULT '',
              surname varchar(100) NOT NULL DEFAULT '',
              passwd char(32) NOT NULL DEFAULT '',
              url varchar(255) NOT NULL DEFAULT '',
              autologin int NOT NULL DEFAULT '0',
              autologout varchar(32) NOT NULL DEFAULT '15m',
              lang varchar(7) NOT NULL DEFAULT 'default',
              refresh varchar(32) NOT NULL DEFAULT '30s',
              theme varchar(128) NOT NULL DEFAULT 'default',
              attempt_failed int NOT NULL DEFAULT 0,
              attempt_ip varchar(39) NOT NULL DEFAULT '',
              attempt_clock int NOT NULL DEFAULT 0,
              rows_per_page int NOT NULL DEFAULT 50,
              timezone varchar(50) NOT NULL DEFAULT 'default',
              role_id bigint unsigned NOT NULL,
              usrgrpid bigint unsigned,
              PRIMARY KEY (userid),
              UNIQUE KEY users_1 (username)
            );
            
            INSERT IGNORE INTO users (userid,username,name,surname,passwd,url,autologin,autologout,lang,refresh,theme,attempt_failed,attempt_ip,attempt_clock,rows_per_page,timezone,role_id,usrgrpid) VALUES (1,'Admin','Zabbix','Administrator','5fce1b3e34b520afeffb37ce08c7cd66','',0,'15m','en_US','30s','default',0,'',0,50,'default',3,7);
          "
          
          echo "Database initialization completed"
        env:
        - name: MYSQL_HOST
          value: "zabbix-mysql"
        - name: MYSQL_DATABASE  
          value: "zabbix"
        - name: MYSQL_USER
          value: "zabbix"
        - name: MYSQL_PASSWORD
          value: "zabbix_password"
