# Zabbix Java Gateway
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-java-gateway
  namespace: zabbix
  labels:
    app: zabbix-java-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-java-gateway
  template:
    metadata:
      labels:
        app: zabbix-java-gateway
    spec:
      containers:
      - name: zabbix-java-gateway
        image: zabbix/zabbix-java-gateway:6.0-alpine-latest
        ports:
        - containerPort: 10052
          name: java-gateway
        env:
        - name: ZBX_START_POLLERS
          value: "5"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          tcpSocket:
            port: 10052
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 10052
          initialDelaySeconds: 5
          periodSeconds: 10

---
# Zabbix Java Gateway Service
apiVersion: v1
kind: Service
metadata:
  name: zabbix-java-gateway
  namespace: zabbix
  labels:
    app: zabbix-java-gateway
spec:
  ports:
  - port: 10052
    targetPort: 10052
  selector:
    app: zabbix-java-gateway
  type: ClusterIP

---
# Zabbix Proxy (Optional - for distributed monitoring)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-proxy
  namespace: zabbix
  labels:
    app: zabbix-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-proxy
  template:
    metadata:
      labels:
        app: zabbix-proxy
    spec:
      containers:
      - name: zabbix-proxy
        image: zabbix/zabbix-proxy-mysql:6.0-alpine-latest
        ports:
        - containerPort: 10051
          name: zabbix-proxy
        env:
        - name: ZBX_PROXYMODE
          value: "0"
        - name: ZBX_HOSTNAME
          value: "zabbix-proxy"
        - name: ZBX_SERVER_HOST
          value: "zabbix-server"
        - name: ZBX_SERVER_PORT
          value: "10051"
        - name: DB_SERVER_HOST
          value: "zabbix-mysql"
        - name: MYSQL_DATABASE
          value: "zabbix"
        - name: MYSQL_USER
          value: "zabbix"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zabbix-db-secret
              key: mysql-password
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"

---
# Zabbix Proxy Service
apiVersion: v1
kind: Service
metadata:
  name: zabbix-proxy
  namespace: zabbix
  labels:
    app: zabbix-proxy
spec:
  ports:
  - port: 10051
    targetPort: 10051
  selector:
    app: zabbix-proxy
  type: ClusterIP
