apiVersion: batch/v1
kind: Job
metadata:
  name: zabbix-db-init
  namespace: zabbix
  labels:
    app: zabbix-db-init
spec:
  template:
    metadata:
      labels:
        app: zabbix-db-init
    spec:
      restartPolicy: Never
      containers:
      - name: zabbix-db-init
        image: zabbix/zabbix-server-mysql:alpine-6.0-latest
        command: 
        - /bin/sh
        - -c
        - |
          set -e
          echo "Waiting for MySQL to be ready..."
          until mysql -h"$MYSQL_HOST" -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" -e "SELECT 1" > /dev/null 2>&1; do
            echo "MySQL is unavailable - sleeping"
            sleep 5
          done
          echo "MySQL is ready"
          
          # Check if database is already initialized
          TABLES_COUNT=$(mysql -h"$MYSQL_HOST" -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" -D "$MYSQL_DATABASE" -e "SHOW TABLES;" 2>/dev/null | wc -l)
          echo "Found $TABLES_COUNT tables in database"
          
          if [ "$TABLES_COUNT" -gt 5 ]; then
            echo "Database is already initialized"
            exit 0
          fi
          
          echo "Initializing Zabbix database schema..."
          
          # Try to find and import the schema files from the Zabbix server image
          if [ -f /usr/share/doc/zabbix-server-mysql/schema.sql.gz ]; then
            echo "Found schema.sql.gz, importing..."
            zcat /usr/share/doc/zabbix-server-mysql/schema.sql.gz | mysql -h"$MYSQL_HOST" -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" "$MYSQL_DATABASE"
            zcat /usr/share/doc/zabbix-server-mysql/images.sql.gz | mysql -h"$MYSQL_HOST" -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" "$MYSQL_DATABASE"
            zcat /usr/share/doc/zabbix-server-mysql/data.sql.gz | mysql -h"$MYSQL_HOST" -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" "$MYSQL_DATABASE"
          elif [ -f /usr/share/doc/zabbix-server-mysql/create.sql.gz ]; then
            echo "Found create.sql.gz, importing..."
            zcat /usr/share/doc/zabbix-server-mysql/create.sql.gz | mysql -h"$MYSQL_HOST" -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" "$MYSQL_DATABASE"
          else
            echo "No schema files found in expected locations, listing available files..."
            find /usr/share/doc -name "*.sql*" 2>/dev/null | head -10
            echo "Trying alternative schema location..."
            if [ -f /usr/share/zabbix-server-mysql/schema.sql.gz ]; then
              zcat /usr/share/zabbix-server-mysql/schema.sql.gz | mysql -h"$MYSQL_HOST" -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" "$MYSQL_DATABASE"
            else
              echo "Schema files not found, database initialization may have failed"
              exit 1
            fi
          fi
          
          echo "Database initialization completed successfully"
        env:
        - name: MYSQL_HOST
          value: "zabbix-mysql"
        - name: MYSQL_DATABASE
          value: "zabbix"
        - name: MYSQL_USER
          value: "zabbix"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zabbix-db-secret
              key: mysql-password
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
