# Simple Database Initialization Job for Zabbix
apiVersion: batch/v1
kind: Job
metadata:
  name: zabbix-db-init-simple
  namespace: zabbix
  labels:
    app: zabbix-db-init
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        app: zabbix-db-init
    spec:
      restartPolicy: OnFailure
      containers:
      - name: mysql-init
        image: mysql:8.0
        command: ["/bin/bash"]
        args:
        - -c
        - |
          set -e
          echo "Waiting for MySQL to be ready..."
          until mysql -h zabbix-mysql -u zabbix -p"$MYSQL_PASSWORD" -e "SELECT 1" > /dev/null 2>&1; do
            echo "MySQL is unavailable - sleeping"
            sleep 5
          done
          echo "MySQL is ready!"
          
          # Check if database is already initialized
          TABLE_COUNT=$(mysql -h zabbix-mysql -u zabbix -p"$MYSQL_PASSWORD" -D zabbix -e "SHOW TABLES;" 2>/dev/null | wc -l)
          echo "Found $TABLE_COUNT tables in database"
          
          if [ "$TABLE_COUNT" -gt 5 ]; then
            echo "Database is already initialized"
            exit 0
          fi
          
          echo "Database is empty, creating a basic schema..."
          
          # Create basic required tables for Zabbix
          mysql -h zabbix-mysql -u zabbix -p"$MYSQL_PASSWORD" zabbix << 'EOF'
CREATE TABLE IF NOT EXISTS users (
  userid bigint unsigned NOT NULL auto_increment,
  username varchar(100) NOT NULL DEFAULT '',
  name varchar(100) NOT NULL DEFAULT '',
  surname varchar(100) NOT NULL DEFAULT '',
  passwd char(32) NOT NULL DEFAULT '',
  url varchar(255) NOT NULL DEFAULT '',
  autologin int NOT NULL DEFAULT '0',
  autologout varchar(32) NOT NULL DEFAULT '15m',
  lang varchar(7) NOT NULL DEFAULT 'default',
  refresh varchar(32) NOT NULL DEFAULT '30s',
  theme varchar(128) NOT NULL DEFAULT 'default',
  attempt_failed int NOT NULL DEFAULT 0,
  attempt_ip varchar(39) NOT NULL DEFAULT '',
  attempt_clock int NOT NULL DEFAULT 0,
  rows_per_page int NOT NULL DEFAULT 50,
  timezone varchar(50) NOT NULL DEFAULT 'default',
  role_id bigint unsigned NOT NULL,
  usrgrpid bigint unsigned,
  PRIMARY KEY (userid),
  UNIQUE KEY users_1 (username)
);

INSERT INTO users (userid,username,name,surname,passwd,url,autologin,autologout,lang,refresh,theme,attempt_failed,attempt_ip,attempt_clock,rows_per_page,timezone,role_id,usrgrpid) VALUES (1,'Admin','Zabbix','Administrator','5fce1b3e34b520afeffb37ce08c7cd66','',0,'15m','en_US','30s','default',0,'',0,50,'default',3,7);
EOF
          
          echo "Basic schema created. Database initialization completed."
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zabbix-db-secret
              key: mysql-password
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
