apiVersion: batch/v1
kind: Job
metadata:
  name: zabbix-db-recreate
  namespace: zabbix
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: db-recreate
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zabbix-db-secret
              key: mysql-root-password
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zabbix-db-secret
              key: mysql-password
        command:
        - /bin/bash
        - -c
        - |
          set -e
          echo "Waiting for MySQL to be ready..."
          until mysql -h zabbix-mysql -u root -p${MYSQL_ROOT_PASSWORD} -e "SELECT 1" &>/dev/null; do
            echo "MySQL not ready, waiting..."
            sleep 5
          done
          echo "MySQL is ready. Recreating database..."
          
          mysql -h zabbix-mysql -u root -p${MYSQL_ROOT_PASSWORD} -e "DROP DATABASE IF EXISTS zabbix;"
          mysql -h zabbix-mysql -u root -p${MYSQL_ROOT_PASSWORD} -e "CREATE DATABASE zabbix CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;"
          mysql -h zabbix-mysql -u root -p${MYSQL_ROOT_PASSWORD} -e "DROP USER IF EXISTS 'zabbix'@'%';"
          mysql -h zabbix-mysql -u root -p${MYSQL_ROOT_PASSWORD} -e "CREATE USER 'zabbix'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';"
          mysql -h zabbix-mysql -u root -p${MYSQL_ROOT_PASSWORD} -e "GRANT ALL PRIVILEGES ON zabbix.* TO 'zabbix'@'%';"
          mysql -h zabbix-mysql -u root -p${MYSQL_ROOT_PASSWORD} -e "FLUSH PRIVILEGES;"
          
          echo "Database recreated successfully!"
  backoffLimit: 3
